object Versions {

    const val appCompat = "1.4.0"
    const val material  = "1.5.0"
    const val constraint = "2.1.2"
    const val coreKtx = "1.7.0"
    const val hilt = "2.42"
    const val tools = "7.0.4"
    const val gson = "2.8.6"
    const val retrofit = "2.9.0"
    const val ok_http = "4.7.2"
    const val logcat = "0.1"
    const val glide = "4.12.0"
    const val lifecycle = "2.4.0-alpha03"
    const val navigation = "2.3.5"
    const val legacy_support = "1.0.0"
    const val recyclerview = "1.2.1"
    const val livedata = "2.4.0"
    const val coroutines = "1.6.0"
    const val viewBinding = "1.0.3"
    const val paging  = "3.1.0"
    const val serialization = "1.3.2"
    const val shimmerVersion = "0.5.0"
    const val kotlinGradlePlugin = "1.6.10"
    const val kotlinSerialization = "1.6.10"
    const val indicator = "4.3"
}